CREATE TABLE BEVERAGE_CATEGORY
(
BEVERAGE_CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
BEVRAGE_TYPE VARCHAR(100)
)

INSERT INTO BEVERAGE_CATEGORY VALUES 
('CLASSIC LEMONADE'),
('STRABERRY FRIZZ'),
('ICED TEA')

CREATE TABLE BEVERAGE_DETAILS
(
BEVERAGE_DETAILS_ID INT PRIMARY KEY,
BEVERAGE_SIZE VARCHAR(100),
BEVERAGE_PRICE DECIMAL(10,2)
)

INSERT INTO BEVERAGE_DETAILS VALUES
(101,'SMALL',2.00),
(102,'MEDIUM',4.00),
(103,'LARGE',10.00)


SELECT * FROM BEVERAGE_CATEGORY
SELECT * FROM BEVERAGE_DETAILS