CREATE TABLE BEVERAGE_CATEGORY
(
BEVERAGE_CATEGORY_ID INT PRIMARY KEY,
BEVERAGE_TYPE VARCHAR(100)
)

INSERT INTO BEVERAGE_CATEGORY VALUES 
(101,'CLASSIC LEMONADE'),
(102,'STRABERRY FRIZZ'),
(103,'ICED TEA')

CREATE TABLE BEVERAGE_DETAILS
(
BEVERAGE_DETAILS_ID INT IDENTITY(1,1) PRIMARY KEY,
BEVERAGE_SIZE VARCHAR(100),
BEVERAGE_PRICE VARCHAR(100),
BEVERAGE_CATEGORY_ID INT,
FOREIGN KEY (BEVERAGE_CATEGORY_ID)
REFERENCES BEVERAGE_CATEGORY(BEVERAGE_CATEGORY_ID) ON DELETE CASCADE,
CONSTRAINT UQ_BEVERAGE_CATEGORY_SIZE UNIQUE (BEVERAGE_CATEGORY_ID, BEVERAGE_SIZE)
)

INSERT INTO BEVERAGE_DETAILS VALUES
('SMALL',2.00,101),
('MEDIUM',4.00,102),
('LARGE',10.00,103),
('SMALL',4.00,102)


SELECT * FROM BEVERAGE_CATEGORY
SELECT * FROM BEVERAGE_DETAILS

 --DROP TABLE BEVERAGE_CATEGORY
 --DROP TABLE BEVERAGE_DETAILS